// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzqctkirvinyohiatbaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cWN0a2lydmlueW9oaWF0YmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODk4MzgsImV4cCI6MjA3MzI2NTgzOH0.DMePH60B1UH2F1TLe-aTWxtz65IC-KnGM5SCCbO5tSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});